nokia/danm

README.md

Correcting the link to the LICENSE file in README.md

Correcting the LICENSE link

---

README.md

A word was repeated unnecessary in the README.md.
"Telco company company" -> "Telco company"

A small correction in README.md

---

README.md

Signed-off-by: Kokan <kokaipeter@gmail.com>

Fix travis link in readme.md

---

README.md
integration/crds/DanmNet.yaml

Correction for some small mistakes

To correct some small mistakes

---

pkg/danm/danm.go

Fixes https://github.com/nokia/danm/issues/9
@antalm 
Testing is ongoing

DANM returns error to kubelet if no network connections are defined

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

documentation
Basic issue and PR templates.
Fixes #4 
None
No

Basic templates for issues and PRs

---

README.md
build/Dockerfile
integration/docker/netwatcher/Dockerfile
integration/docker/svcwatcher/Dockerfile

>
> bug
> cleanup
> design
> failing-test
> feature
It is said in the README that "This will first build the Alpine 3.8 based builder container", but in build/Dockerfile, it is still alpine:3.7. Actually I think we do not need to specify the version at all, just use the latest version should be ok.
Fixes the mismatch of alpine version descriptions.
NONE
NONE

Need not specify alpine version

---

README.md
pkg/ipam/ipam.go
pkg/svcwatcher/controller.go
schema/DanmNet.yaml
schema/network_attach.yaml

documentation
Describing the current status of IPv6, and dual-stack support.
Fixes https://github.com/nokia/danm/issues/30

Expanding README with chapter about IPv6, and dual-stack support

---

.travis.yml
build_danm.sh
pkg/bitarray_test/bitarray_test.go
pkg/cnidel/cnidel.go
pkg/cnidel_test/cnidel_test.go
pkg/stubs/netclient_stub.go
run_uts.sh

Enable unit tests in Travis

---

README.md
example/device_plugin_demo/sriov_pod.yaml

documentation
Tries to explain the general Device Plugin approach and provides an sriov specific example for using Device Plugin capability
Fixes #
```release-note
```

Add "Device Plugin support" and "Using SR-IOV CNI" chapters to README

---

build_danm.sh
pkg/cnidel/cnidel.go

bug
**Which issue(s) this PR fixes** *
Fixes #55 (hopefully :) )

Properly delete all network interfaces of a Pod

---

pkg/danm/danm.go
pkg/danm/danm_test.go

failing-test
Unit Test and increases code coverage
Fixes #
```release-note
NONE
```

add unit TC to PopDevice function

---

pkg/cnidel/cnidel.go
pkg/syncher/syncher.go
test/uts/syncher_test/syncher_test.go

Title says it all
Tests also have quite a good conditional coverage as well IMO, although haven't measured.

Adding tests to achieve 100% UT coverage for syncher package

---

build_docker.sh

>
> bug
> cleanup
> design
> failing-test
> feature
Make sure the base image alpine:latest is up to date before building DANM
NONE
NONE
NONE

Make sure alpine:latest is up to date

---

README.md

>
> bug
> cleanup
> design
> failing-test
> feature
Correct the go get command in README
NONE
NONE
NONE

Correct small mistake in README

---

logo_w_name.svg

documentation
A logo with the name on it. 
None
NONE

Adding logo with name

---

integration/crds/ClusterNetwork.yaml
integration/crds/TenantConfig.yaml
integration/crds/TenantNetwork.yaml
schema/ClusterNetwork.yaml
schema/TenantConfig.yaml
schema/TenantNetwork.yaml
schema/network_attach.yaml

Say hello to my little friends ClusterNetwork, TenantNetwork, and TenantConfig!

DANM 4.0 EP2: Adding the CRD and API schema for the new, DANM 4.0 APIs

---

CONTRIBUTING.md

>
> bug
> cleanup
> design
> failing-test
> feature
Fixes #
```release-note
```

Adding slack channel link and registration link

---

CONTRIBUTING.md
README.md

documentation
Working Slack invite link
None
None
No

Slack invite link update

---

pkg/admit/validators.go
test/uts/admit_tests/netadmit_test.go

Fixing https://github.com/nokia/danm/issues/136.

Add new validation forbidding bigger than /8 CIDRs

---

README.md

>
> bug
> cleanup
> design
documentation
> failing-test
> feature
**What does this PR give to us**: clearer documentation
N/A
**Special notes for your reviewer**: N/A
**Does this PR introduce a user-facing change?**: NONE
```release-note
```

Fixed line break and warning label

---

integration/manifests/svcwatcher/svcwatcher_ds.yaml
integration/manifests/webhook/webhook.yaml

>
bug
> cleanup
> design
> failing-test
> feature
1. Change the image name of webhook's manifest yaml to fit the DANM setup instruction.
2. Add the image pull policy to svcwatcher daemonSet
Fixes #141 
NONE

Enhance the manifests of webhook and svcwatcher #141

---

README.md

Moved binaries description to introduction, only list left in ch. building the binaries
documentation
Fixes #
NONE
```release-note
```

Binaries description moved

---

README.md

documentation
Fixes #
NONE
```release-note
```

Re-phrased some parts

---

README.md
deployment-guide.md

>
documentation
Fixes #
**Does this PR introduce a user-facing change?**: NONE
```release-note
```

Moved deployment guide to its own page.

---

pkg/admit/validators.go

>
bug
> cleanup
> design
> failing-test
> feature
Fixes #163 
NONE
NONE

do not check danmnet name length if it does not use vxlan/vlan

---

pkg/cnidel/cnidel.go
pkg/danmep/ep.go
pkg/ipam/ipam.go
pkg/metacni/metacni.go
test/uts/ipam_test/ipam_test.go

Solves https://github.com/nokia/danm/issues/173

Enable IPv6 on a network interface when "none" IP allocation scheme is used

---

pkg/danmep/danmep.go
pkg/danmep/ep.go

Solves https://github.com/nokia/danm/issues/180

Disabling DAD on DANM allocated IPv6 addresses

---

schema/ClusterNetwork.yaml
schema/DanmNet.yaml
schema/TenantNetwork.yaml
user-guide.md

documentation
Fix the doc/schema descriptions.
None.
Yes, because users read docs.

Fix the doc/schema descriptions to the new NetworkID limit (11->10)

---

crd/apis/danm/v1/types.go

cleanup
Remove unnecessary duplicate definition in danm types, enabling better type handling in general.
```release-note
NONE
```

Allign types: DanmNet, TenantNetwork, Clusternetwork

---

build_danm.sh
integration/install/danm-installer.yaml
schema/DanmNet.yaml

cleanup
Changes the `damn`-s to `danm` where they are typos. 
- labelling of danm-installer container
- Desription of DanmNet
Fixes none
None
I'm not really sure if this is a real user facing change...
```release-note
- build_danm.sh tags danm-installer correctly
```

Changing some damn-s to danm-s

---

pkg/danmep/ep.go

fixes https://github.com/nokia/danm/issues/228
DANM now sets the link Id into the netlink Route object, making sure the kernel attaches the IP route to the correct device.

Set LinkID into the netlink Route object when creating an IP route
