- pkg/watcher/watcher.go
netwatcher wrote the following error log even though --kubeconf argument was not provided and should have used InClusterConfig instead.
/ # /usr/bin/watcher
`2018/10/17 11:33:52 Starting DANM Watcher...
2018/10/17 11:33:52 ERROR: Parsing kubeconfig failed with error:stat admin.conf: no such file or directory , exiting`
Default admin.conf value is now removed from kubeconf flag to allow the usage of InClusterConfig.
> Netwatcher uses InClusterConfig if --kubeconf argument is not provided.

- .gitignore
- .travis.yml
- README.md
This is just something very basic.
* there was a nasty dependency on `$GOPATH` environment variable, just plain simple removed it
* creates and maps current dir `bin/` where the executables going to be saved (the mkdir part maybe not ideal)
* added `.gitignore` for the created files
* build status logo for master
Fixes #3
> Minimal travis support

- integration/manifests/svcwatcher/svcwatcher_ds.yaml
... for vanilla K8S setup
For clusters created by i.e. kubeadm, the master nodes differentiator label seems to be node-role.kubernetes.io/master without any value.
This change proposed to have this in the sample manifest.
> Align the svcwatcher nodeselector

- README.md
- integration/manifests/netwatcher/0netwatcher_rbac.yaml
- integration/manifests/netwatcher/netwatcher_ds.yaml
- integration/manifests/svcwatcher/0svcwatcher_rbac.yaml
- integration/manifests/svcwatcher/svcwatcher_ds.yaml
This PR avoids the usage of hostpath mounts on every node and uses RBAC for the two Danm daemonsets. It allows in-cluster config for kube clients smoothly. The needed role content is reverse engineered and seems working, but please take a look, might be too much or too less still 😇.
> RRAC for net and svcwatcher

- README.md
- integration/crds/DanmNet.yaml
- pkg/cnidel/cnidel.go
- pkg/crd/apis/danm/v1/types.go
- pkg/danm/danm.go
- pkg/danmep/ep.go
- pkg/glide.lock
- schema/DanmNet.yaml
Implements solution to https://github.com/nokia/danm/issues/15
Container_prefix API attribute became optional.
A NIC connecting to a network having it set will continue to be name accordingly.
A NIC connecting to a network not having it set will be dynamically provisioned
a Pod-unique name in Pod Instantiation time.
Enhancement works for in-built IPVLAN, static delegates, and dynamic delegates!
> Introduce dynamic container interface naming as a fallback option

- README.md
- pkg/danm/danm.go
feature
Admin is now able to provision a (single) default network (a danmnet resource with name: "default") in the target kubernetes namespace, which will be used when there is nothing defined in the annotation section of a Pod/Controller.
Fixes #21 
```release-note
Admin is now able to provision a (single) default network (a danmnet resource with name: "default") in the target kubernetes namespace, which will be used when there is nothing defined in the annotation section of a Pod/Controller.
```
> Default net

- README.md
- pkg/cnidel/cniconfs.go
- pkg/cnidel/cnidel.go
- pkg/cnidel/types.go
- pkg/danm/danm.go
- pkg/danmep/danmep.go
- pkg/danmep/ep.go
- pkg/danmnet/danmnet.go
- pkg/danmnet/net.go
- pkg/glide.lock
- schema/DanmNet.yaml
- schema/network_attach.yaml
This will enable the creation of MACVLAN interfaces based on the dynamic DanmNet API.
The CNI used to create the interfaces is the basic CNI coming from:
https://github.com/containernetworking/plugins/blob/master/plugins/main/macvlan/macvlan.go
Interfaces are created in bridge mode, with 1500 MTU.
Change is not yet tested.
> Integrate MACVLAN CNI to DANM with dynamic integration level + Extend IP route provisioning support to ALL backends

- build/build.sh
- pkg/crd/apis/danm/v1/types.go
- pkg/danmnet/danmnet.go
- pkg/danmnet/net.go
- pkg/ipam/ipam.go
- pkg/ipam_test/ipam_test.go
Automatic conversion between bool and string does not work anymore for some reason with K8s 1.13.4 + latest client generator code, so DanmNet attribute "Validation" cannot be decoded nomo'.
It is anyway stupid to treat it as string, so changed the type in the schema.
But, I had enough of this ... generators on this ... project, so their version is explicitly fixed now in the SCM pipeline.
Unnecessary CGO directive and overly verbose generator log level settings were also removed.
We only had one user sighting of this issue so far, but just in case I create the PR for the fix.
If anyone else see this error in their kubelet logs
"NetworkPlugin cni failed to set up pod "test-danm-dep-5597498784-7rlkh_default" network: CNI network could not be set up: failed to get DanmNet due to:NID:test-net …
> Fixing possible 1.13.4 K8s client type incompatibility issue

- pkg/ipam/ipam.go
- pkg/netcontrol/net.go
- pkg/netcontrol/netcontrol.go
- test/stubs/client_stub.go
- test/stubs/clientset_stub.go
- test/stubs/netclient_stub.go
- test/uts/cnidel_test/cnidel_test.go
- test/uts/ipam_test/ipam_test.go
Bugs caught and corrected during UTing this package:
1: Last IP from the allocation pool was never used
2: When Pool.End was not provided, we set the first IP into this parameter, rather than the last.
This has resulted in failing validation for a subnet providing only CIDR without allocation pool
3: Static IPs were not validated against the allocation pool
4: When the allocation pool is entirely exhausted, we did not explicitly return an error, but let DANM proceed with setting up an interface without an IP. This has been changed now
> 100% coverage for ipam package - and bugfixes

- pkg/cnidel/cnidel.go
>
bug
> cleanup
> design
> failing-test
> feature
Fixes #66 
'PATH' is needed by Weave.
Since we want to pass the minimum environment variables to delegates, I think we will need to specify the cniType when apending the environment variables other than CNI_X.
NONE
> Transfer PATH environment variable when delegating weave

- README.md
- glide.lock
- pkg/cnidel/cniconfs.go
- pkg/cnidel/cnidel.go
- pkg/danmep/ep.go
- schema/DanmNet.yaml
Next up on the what we could do better in DANM is the cnidel package!
The following operability enhancements are also introduced as part of this PR:
- the CNI config file to be used when delegating to static integration level backends is now configurable via the NetworkID DanmNet API parameter
- the directory where the static CNI configuration files are searched for is now also configurable, via the CNI_CONF_DIR environment variable (default value is the current hard coding for the sake of backward compatibility)
README and DanmNet schema files were also deserving of some major face lifting.
> Quality of life enhancements for CNI delegation code

- glide.lock
- glide.yaml
- pkg/danmep/danmep.go
- pkg/metacni/metacni.go
feature
DANM takes care of IPv6 related sysctls before CNIs are invoked.
Fixes #68 
Tested with ipvlan inside VMs.
None.
> Set IPv6 related sysctls, if at least one IPv6 CIDR is set on any interfaces

- cmd/cnitest/cnitest.go
- cmd/fakeipam/fakeipam.go
- crd/apis/danm/v1/types.go
- pkg/cnidel/cniconfs.go
- pkg/cnidel/cnidel.go
- test/uts/cnidel_test/cnidel_test.go
feature
Add Dual stack IPv6 support for external CNIs and fakeipam.
**Which issue(s) this PR fixes**
Fixes #73 
It is under testing, but please review it whether this PR is conceptually ok.
NONE
> Dual stack IPv6 support for external CNIs and fakeipam

- pkg/danmep/danmep.go
feature
More sysctls need to be set for IPv6.
Enhances #68 
NONE
> More sysctls to set for IPv6

- README.md
- crd/apis/danm/v1/types.go
- pkg/cnidel/cnidel.go
- pkg/metacni/metacni.go
- schema/DanmNet.yaml
- test/uts/cnidel_test/cnidel_test.go
Currently this API attribute means "exact name of a container" interface, but it was never the original intention.
It was just a temporary change I needed to administer when we have moved to the asynchronous interface provisioning method.
Even the name suggest this is just a prefix of the NICs :)
Functionally speaking this makes it hard to attach multiple NICs to the same DanmNet.
After this change implicit and explicit naming schemes will be aligned: in both cases we will postfix the interface names with the provisioning sequence number.
> Fixing the meaning of "container_prefix" API attribute

- README.md
- crd/apis/danm/v1/types.go
- pkg/cnidel/cnidel.go
- pkg/metacni/metacni.go
- test/uts/cnidel_test/cnidel_test.go
The project assumes that a DanmNet's NetworkID and ObjectMeta.Name parameters always match.
This is even outlined in the schema descriptor.
However, recently we have introduced some changes which broke this assumption.
First, with the "default" feature, and then lately with the variable static delegate configuration.
The user might not even perceive it, but as a result of these changes interfaces weren't properly cleaned-up during CNI DEL invocations.
Instead of re-writing the whole codebase, we save the real name of the network as well into the interface's DanmEp, and use this parameter when we read the network descriptor during the deletion of the interface.
Meaning of NetworkID parameter left untouched in all the other places, but eventually, we need to revise when to sue which …
> Fixing iface deletion bug when netIds don't match

- glide.lock
- pkg/danmep/ep.go
fix
fix IPv6 gARP issue, cleaner code
Fixes #75 
Now it produces valid gARP packet, but I keep it as WIP until I can test it on a bare metal system where I have access to the switches. 
NONE
> Replace external arping binary execution with Go implementation

- crd/apis/danm/v1/types.go
- pkg/cnidel/cnidel.go
- pkg/ipam/ipam.go
- pkg/metacni/metacni.go
- pkg/netcontrol/netcontrol.go
- pkg/svccontrol/controller.go
- pkg/svccontrol/utils.go
- schema/DanmNet.yaml
- schema/DanmService.yaml
- schema/network_attach.yaml
- test/stubs/epclient_stub.go
- test/uts/ipam_test/ipam_test.go
Continuation of https://github.com/nokia/danm/pull/80
After an impromptu author round-table discussion, it was decided that the whole project shall consistently use ObjectMeta.Name attribute when referring to a DanmNet.
This PR finishes the job.
NetworkID shall control only the following functionality:
- Influence name of VxLAN host interface
- Influence name of VLAN host interface
- Define which CNI config file to be used for a static delegate
> Changing the rest of the codebase to consistently use ObjectMeta.Name

- cmd/cnitest/cnitest.go
- cmd/fakeipam/fakeipam.go
- cmd/webhook/webhook.go
- crd/apis/danm/v1/types.go
- glide.lock
- glide.yaml
- integration/manifests/webhook/webhook.yaml
- pkg/cnidel/cniconfs.go
- pkg/cnidel/cnidel.go
- pkg/cnidel/types.go
- pkg/datastructs/datastructs.go
- pkg/metacni/metacni.go
- pkg/netadmit/netadmit.go
- pkg/netadmit/validators.go
- pkg/netcontrol/netcontrol.go
- pkg/svccontrol/controller.go
- test/stubs/client_stub.go
- test/stubs/netclient_stub.go
Fortunately it is pretty slick thanks to the generic validating structure introduced in EP1.
Existing validating rules, and the validating interface itself was updated to be able to define separate rules for MODIFY operations. This was a must have for TenantNetworks, but also comes handy in the validation of spec.Options.Alloc.
Still need to figure out the best way of adding TenantConfigs to the generic framework.
> DANM 4.0 EP3: Validating and mutating Webhook is expanded with new rules to cover the newly introduced APIs

- cmd/netwatcher/netwatcher.go
- crd/apis/danm/v1/register.go
- crd/apis/danm/v1/types.go
- integration/crds/TenantNetwork.yaml
- integration/manifests/netwatcher/0netwatcher_rbac.yaml
- pkg/admit/netadmit.go
- pkg/admit/utils.go
- pkg/netcontrol/netcontrol.go
- schema/TenantConfig.yaml
- test/stubs/client_stub.go
Binary is reworked to be able to hold, and run more than one Controllers/Informers.
NetWatcher will hold 3 of them from now on: DanmNet, TenantNetwork, and ClusterNetwork.
It does not matter which API is getting modified, NetWatcher will handle them the exact same way.
> DANM 4.0 EP5: Adapting netwatcher to create VLAN and VxLAN interfaces for all APIs

- crd/apis/danm/v1/types.go
- integration/cni_config/danm_rbac.yaml
- pkg/admit/netdel.go
- pkg/cnidel/cnidel.go
- pkg/datastructs/datastructs.go
- pkg/ipam/ipam.go
- pkg/metacni/metacni.go
- pkg/netcontrol/netcontrol.go
- schema/TenantConfig.yaml
- test/uts/cnidel_test/cnidel_test.go
This requires basically changing the code which deals with the external interfaces -both uplink and downlink-, but does not require us to re-write everything.
We only need to convert everything to DanmNet type, then the internals continue to work as-is.
Refactoring happened where it was absolutely required, for example in the handling of the annotation, and the default networks.
The code generally only got better.
> DANM 4.0 EP6: Adapting CNI code to work with all the APIs

- integration/manifests/svcwatcher/0svcwatcher_rbac.yaml
- pkg/netcontrol/netcontrol.go
- pkg/svccontrol/controller.go
- pkg/svccontrol/utils.go
- schema/DanmService.yaml
We do this by adding two new network selectors into the DANM compatible Service API schema.
Each network API has its own, explicit selector, independent from each other.
Thus it becomes possible for users to explicitly control which management API they want their EndPoints to select. This functionality is needed, because the different APIs can contains networks with the exact same name, even within the exact same namespace (e.g. if someone would use DanmNet and TenantNetwork together, for some reason)
> DANM 4.0 EP7: Adapting Svcwatcher code to independently recognize the three network management APIs

- pkg/cnidel/cnidel.go
- pkg/danmep/danmep.go
- pkg/metacni/metacni.go
- pkg/syncher/syncher.go
Finally caught a very nasty race-condition / edge use-case present since 3.2.
The root cause is that in some cases we have returned earlier during interface creation, than starting the asynch thread.
But if some other threads have already progressed to the point of forking, they were basically prematurely reaped by the early termination of the whole process, and/or by the subsequent and almost immediately triggered CNI_DEL.
Really nasty :)
Resolution is getting rid of ALL early return cases once we have progressed to interface creation. In case of an early failure we simply push the result in to the syncher object, even if the error happened in the main thread.
Only Syncher can return from the main thread, no sooner and no later than all results are available: be them pushed from the main …
> Some interfaces are not properly cleaned during CNI_ADD if some other interface creations fail

- cmd/webhook/webhook.go
- pkg/admit/confadmit.go
- pkg/admit/netadmit.go
- pkg/admit/netdel.go
- pkg/admit/validators.go
- pkg/confman/confman.go
- schema/TenantConfig.yaml
- test/stubs/client_stub.go
- test/stubs/clientset_stub.go
- test/stubs/tconfclient_stub.go
- test/utils/utils.go
- test/uts/cnidel_test/cnidel_test.go
- test/uts/confman_test/confman_test.go
- test/uts/ipam_test/ipam_test.go
Started adding UTs for new 4.0 confman package.
Refactoring is -again- needed to be able to test the new changes:
- for easy future extension stub instantiation now takes one struct called TestArtifacts
- webhook function are refactored to use a pre-created DANM client as a member of a struct, rather than everyone using their own
The original approach was unstubbable, the new -hopefully- won't run into race conditions
> UTs for newly introduced confman package

- README.md
Changing the link of the Akraino REC blueprint family to a link ot the Akraino REC architecture ans the intall guide.
>
> bug
> cleanup
> design
documentation
> failing-test
> feature
Better links to Akraino REC
None
None
None
> Link to the Akraino REC architecture and install guide

- README.md
- cmd/cnitest/cnitest.go
- pkg/cnidel/cniconfs.go
- pkg/cnidel/cnidel.go
- pkg/ipam/ipam.go
- schema/ClusterNetwork.yaml
- schema/DanmNet.yaml
- schema/TenantNetwork.yaml
- schema/network_attach.yaml
- test/stubs/danm/client_stub.go
- test/stubs/danm/clientset_stub.go
- test/stubs/danm/netclient_stub.go
- test/utils/utils.go
- test/uts/cnidel_test/cnidel_test.go
- test/uts/ipam_test/ipam_test.go
Changing IPAM code in cnidel so centralized API driven IPAM now works for all backends requesting it!
All includes static.
If cidr/net6 is included in the network manifest, and the Pod's connection request includes "ip" / "ip6"; DANM will call ipam.Reserve and overwrite the "ipam" key in the CNI config of the static delegate with its own fakeipam integration.
This will result in CNI compliant static backends too getting their IPs purely based on a centralized network management API. 
Also MACVLAN plugin recently was enhanced to tolerate the absence of "ipam" key in the CNI config. As a result "ip":"none" is now enabled for all backends.
The user will be responsible of making sure unsupported IPAM request types are not used for backends not supporting it; and that only CNI standard …
> DANM centralized, API driven API management extended to work for all CNI compliant backends

- pkg/confman/confman.go
- test/stubs/danm/client_stub.go
- test/stubs/danm/clientset_stub.go
- test/stubs/danm/netclient_stub.go
- test/stubs/danm/tconfclient_stub.go
- test/utils/utils.go
- test/uts/admit_tests/confadmit_test.go
- test/uts/admit_tests/netdel_test.go
- test/uts/cnidel_test/cnidel_test.go
- test/uts/confman_test/confman_test.go
- test/uts/ipam_test/ipam_test.go
We check if the right VNI in the right iface profile was freed, and also check that nothing else was!
Moved the struct definition used by the stubs to util package to avoid circular dependency.
> Added UTs for admit/netdel.go

- integration/crds/lightweight/DanmNet.yaml
- integration/crds/production/ClusterNetwork.yaml
- integration/crds/production/TenantConfig.yaml
- integration/crds/production/TenantNetwork.yaml
Fixes https://github.com/nokia/danm/issues/112
Note: DanmEp is not meant to be a user-facing API. It only used to store state information internal to DANM.
Therefore we actually don't want DanmEps to show up in generic queries, to avoid overloading the user with unnecessary , and irrelevant information.
> Add "categories: all" to all public CRD API definition

- pkg/metacni/metacni.go
Core happens when a Device dependent network did not get any allocated, e.g. SR-IOV Pod did not ask VF Devices from its Pod manifest, but defined an SR-IOV network connection.
> Fix a core in metacni

- cmd/danm/danm.go
- cmd/fakeipam/fakeipam.go
- integration/cni_config/00-danm.conf
- pkg/cnidel/cnidel.go
- pkg/datastructs/datastructs.go
- pkg/metacni/metacni.go
- test/stubs/danm/netclient_stub.go
- test/uts/cnidel_test/cnidel_test.go
- test/uts/ipam_test/ipam_test.go
A bug is corrected both in cnidel, and metacni package related to Free-ing IPs when an error happened during the execution of the same asynch thread.
The correction is to immediately refresh the network manifest after allocation to avoid working on an out-of-date local copy.
This bug is probably present from earlier, accidentally caught during testing.
CNI version support is now explicitly set to 0.3.1 to avoid any accidental mistranslation of CNI results.
Started correctly filling IPAM config for static CNI deletes when DANM was reserving their IP during setup.
DANM CNI log file can be found under /ar/log/danm.log from now on!
> Various CNI delegation corrections related to framework bump, and central IPAM support

- integration/manifests/webhook/webhook.yaml
>
bug
> cleanup
> design
> failing-test
> feature
**What does this PR give to us**: With this fix, webhook will be able to access `danmeps` resources, which is required now.
Fixes #
**Special notes for your reviewer**: NONE
**Does this PR introduce a user-facing change?**: NONE
```release-note
Enable access right to danmeps resource from webhook cluster role
```
> Enable access right to danmeps resource from webhook cluster role

- README.md
- integration/manifests/webhook/webhook-create-signed-cert.sh
- integration/manifests/webhook/webhook-patch-ca-bundle.sh
- integration/manifests/webhook/webhook.yaml
>
> bug
> cleanup
> design
> failing-test
feature
Added a shell script which generates the cert and key pair for the webook, and puts it in a kubernetes secret, from which the webhook can easily access it.
Added another shell script which provides the CA bundles for the webhook.
Modified the webhook.yaml file to fit the above mentioned changes.
Modified the README.md file to provide instructions on how to use the scripts when setting up the webhook.
**Special notes for your reviewer**: None
**Does this PR introduce a user-facing change?**: Yes
```release-note
Users need to redeploy the webhook based on the new instructions given in the README.md file.
```
> Provide webhook with certificates in an easy way

- pkg/svccontrol/controller.go
cleanup
Currently svcwatcher is very noisy. It generates too many log entries, because all the function calls are logged. This PR sets the verbosity level of these info/debug messages to 5, so they will be suppressed by default. Such detailed logging can be enabled by `-v=5` commandline parameter.
**Which issue(s) this PR fixes**
Fixes #14 
I know that you have plans to replace glog to something better, but this fix is kindof urgent to reduce fluentd load and save log data store capacity.
NONE
> Set verbosity level on info/debug messages to reduce unnecessary logging

- example/routes_and_proutes/cnet_with_route.yaml
- example/routes_and_proutes/output.txt
- example/routes_and_proutes/pod_with_proutes.yaml
- example/svcwatcher_demo/deployments/internal_processor.yaml
- example/svcwatcher_demo/deployments/loadbalancer.yaml
- schema/network_attach.yaml
How to provision IP routes exactly either into the default, or into a custom routing table inside a Pod are our most ambiguous features according to user feedback.
To address the issue I added couple of examples showcasing these features, and exhibiting the expected result!
> Expanding documentation and examples related to handling IP routes

- .travis.yml
- build_docker.sh
- run_uts.sh
- scm/build/Dockerfile
- scm/ut/Dockerfile
Because of build reproducibility, but also to make sure the recently discovered security issues in the os, and net packages are all fixed in our binaries.
> Explicitly set the Go version used inside the project to 1.12.9

- README.md
- cmd/danm/danm.go
- integration/manifests/webhook/webhook.yaml
- pkg/netcontrol/netcontrol.go
- pkg/syncher/syncher.go
- test/uts/syncher_test/syncher_test.go
See https://github.com/nokia/danm/issues/144 for the whole story.
I also increased the maximum allowed timeout value for Pod level ADD and DEL operations after a week spent with extensive etcd performance profiling.
Unrelated: you should really upgrade to ETCD 3.14, it is the real deal :)
> Performance improvements to concurrent Pod creations, and deletions

- crd/apis/danm/v1/types.go
- glide.lock
- glide.yaml
- pkg/cnidel/cniconfs.go
- pkg/cnidel/cnidel.go
- pkg/cnidel/types.go
- pkg/danmep/danmep.go
- pkg/danmep/ep.go
- pkg/metacni/metacni.go
- test/utils/utils.go
- test/uts/cnidel_test/cnidel_test.go
- user-guide.md
PR solves bullet point 2 described in https://github.com/nokia/danm/issues/148.
It also makes sure to skip kernel tunings for interfaces which are actually not managed by the kernel.
> Adding support for Intel Fortville + DPDK use-case

- pkg/confman/confman.go
- test/uts/confman_test/confman_test.go
Both in Reserve() and Free() calls core can theoretically occur when
the chosen interface profile does not have "Alloc" initialized.
This practically can only occur if a network was created in env
where webhook was not running.
If everything was done according to the install guide this shall never occur, but it is better to be on the safe side.
> Adding safeguards against  a potential core situation in confman

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- cmd/danm/danm.go
- cmd/netwatcher/netwatcher.go
- cmd/svcwatcher/svcwatcher.go
- cmd/webhook/webhook.go
- scm/build/build.sh
Solves https://github.com/nokia/danm/issues/143
Simply calling any of the major DANM binaries with the "-version" flag will result in version, and commit hash information printed to standard out.
This information is automatically baked into the binaries by the SCM scripts during linking.
Exact version information will make debugging helluva lot easier!
> Add "-version" option to all DANM binaries

- crd/apis/danm/v1/register.go
- pkg/confman/confman.go
- test/stubs/danm/client_stub.go
- test/stubs/danm/tconfclient_stub.go
- test/utils/utils.go
- test/uts/confman_test/confman_test.go
When multiple TenantNetworks are being created / deleted at the same time, some of updates can be rejected by the API server with HTTP 409.
Proper handling in such cases is to refresh the TenantConfig object, and try the update again.
Both Reserve and Free APIs are updated to handle contention the right way.
> Fixing the handling of parallel TenantConfig Updates in confman

- cmd/cnitest/cnitest.go
- crd/apis/danm/v1/types.go
- pkg/admit/validators.go
- pkg/bitarray/bitarray.go
- pkg/cnidel/cnidel.go
- pkg/ipam/ipam.go
- pkg/metacni/metacni.go
- test/stubs/danm/netclient_stub.go
- test/utils/utils.go
- test/uts/bitarray_test/bitarray_test.go
- test/uts/cnidel_test/cnidel_test.go
- test/uts/ipam_test/ipam_test.go
Implementing the functional part of https://github.com/nokia/danm/issues/147, removing the restriction related to usable V6 prefixes.
Uses the new API attributes introduced in https://github.com/nokia/danm/pull/177.
As part of the change some generic aspects of IPAM are also streamlined:
- static IP addresses can now be provided in a simple IP format, no need for the prefix anymore (but prefixed format continues to work)
- MAC address is not needed as IPv6 allocation won't be based on random EUI64 anymore (but the DanmEp schema remains unchanged again for backward compatibility reasons)
- when an IPv6 address is requested from a network without Alloc6 and Pool6, ipam will automatically initialize these attributes. doing so apps will not be required to migrate their network objects to be …
> Change random EUI64 based IPv6 allocation scheme to be allocation pool based

- pkg/ipam/ipam.go
When an IP is dynamically allocated we save it into Pool/Pool6. Next time searching for the first free IP will start from the associated index, rather than from zero.
This should accelerate allocation time for huge allocation pools (4/8M).
Works with both V4/V6 subnets!
> Optimize dynamic IP allocation algorithm by storing the last dynamically allocated IP

- crd/apis/danm/v1/types.go
- pkg/cnidel/cniconfs.go
- pkg/cnidel/cnidel.go
- pkg/cnidel/types.go
- pkg/danmep/danmep.go
- pkg/danmep/ep.go
- pkg/datastructs/datastructs.go
- pkg/ipam/ipam.go
- pkg/metacni/metacni.go
- pkg/netcontrol/netcontrol.go
- test/uts/cnidel_test/cnidel_test.go
Umbrella ticket to fully solve https://github.com/nokia/danm/issues/166 and https://github.com/nokia/danm/issues/165, and partially https://github.com/nokia/danm/issues/167.
In the new structure DanmEps will never be cleaned when its related IPs could not be freed in the network for any reason. In these scenarios it will become either user, or Cleaner's responsibility to handle the dangling resources.
> Increase resiliency of critical execution paths against temporary, or permanent network outages

- integration/manifests/netwatcher/netwatcher_ds.yaml
- integration/manifests/svcwatcher/svcwatcher_ds.yaml
As per Kubernetes 1.16, DaemonSet API v1betaX is deprecated and using v1 is recommended.
https://v1-16.docs.kubernetes.io/docs/setup/release/notes/#deprecations-and-removals.
As v1.17 is now listed as a supported version in the deployment guide, it seems to make sense
to update the daemonset to API version 1.
bugfix
A daemonset resource configuration that loads into K8s v1.17 without errors :-)
NONE.
API v1 existed since Kubernetes v1.9, and older versions are already declared 'not supported' in the deployment guide - so for users who are running a supported version, there should be no change.
> Update DaemonSet API to v1

- deployment-guide.md
- integration/cni_config/00-danm.conf
- integration/cni_config/danm_rbac.yaml
- integration/cni_config/example_kubeconfig.yaml
Configure the DANM CNI kubeconfig file with a ServiceAccount rather
than a (human) user account.
Also, update deployment-guide with steps how to create such user
account and extract the token, and update the example kubeconfig
file such that it references variable names used in the
deployment-guide. (This should effectively allow readers to create
the kubeconfig file simply by running "envsubst" if they followed
the deployment guide exactly.)
documentation
Somewhat more user-friendly documentation (explicit steps to create a DANM account, rather than
an example kubeconfig file that refers to an exiting user key/cert with little guidance on how to
create that), and a configuration that's somewhat more inline with Kubernetes …
> Use DANM CNI ServiceAccount rather than user account

- integration/manifests/svcwatcher/0svcwatcher_rbac.yaml
Seeing following error in svcwatcher log,
'User "system:serviceaccount:kube-system:svcwatcher" cannot
create resource "events" in API group "" in the namespace "kube-system"'.
Adding this API to svcwatcher RBAC.
bug
NONE
> Grant Events Create permission to svcwatcher RBAC

- cmd/svcwatcher/svcwatcher.go
- go.mod
- pkg/metacni/metacni.go
- pkg/svccontrol/controller.go
DANM svcwatcher managed EndPoints now support IPv6 addresses as well!
also correcting https://github.com/nokia/danm/issues/185
Correction is not the elegant one, but should work with the current architectural constraints.
We will infinitely re-try EndPoint update in case of conflict, but only retry for 1 sec in case of temporary network outages etc.
> Adding V6 support to svcwatcher, plus fixing concurrent updates

- pkg/metacni/metacni.go
Fix issue where in meta CNI where if an error during createNic()
might result in a possible nil pointer dereference during error
handling
bug
A fix for issue #198 . Maybe not in the right way - please review and let me know.
**Which issue(s) this PR fixes**
Fixes #198 
NONE
> Fix possible nil derefernce in metacni error handling

- pkg/svccontrol/controller.go
Fixing https://github.com/nokia/danm/issues/191
When handling an API event related to thes objects, svcwatcher unnecessrily
interrogated ALL existing objects.
It is fixed now by always using the namespace awarre lister client API instead the generic.
> Fixing too generic Endpoint, DanmEp, Services, and Pod interrogation in svcwatcher

- pkg/svccontrol/controller.go
Solves https://github.com/nokia/danm/issues/203
This is needed to be inline with how K8s in-built Service controller creates its own EPs.
Not doing so might break assumptions hard-coded into external DNS Controllers, such as CoreDNS.
Svcwatcher created EndpointAddresses after the modification for a StatefulSet managed Pod:
- hostname: internal-processor-set-4
ip: 10.240.1.104
nodeName: 172.31.3.157
targetRef:
kind: pod
name: internal-processor-set-4
namespace: default
resourceVersion: "12491055"
uid: a20958ed-9196-433d-a75d-e3200f233f8d
> Add Pod UID and Nodename parameters to svcwatcher created EndPoints

- pkg/danmep/ep.go
A dual-stack network can include both IPv4 and V6 CIDRs, allocation pools, and IP routes.
But not every Pod connecting to a DS network will have DS interfaces.
So, IP routes need to be selectively created; only if an IP was really assigned to the iterface from its respective domain.
Otherwise Linux throws a "no route to host" error during route creation, which in turn fails Pod instantiation.
> Fixing default table route management to work in all dual-stack cases

- integration/crds/lightweight/DanmNet.yaml
- integration/crds/production/ClusterNetwork.yaml
- integration/crds/production/TenantNetwork.yaml
Kubernetes provides pre-defined [string validation formats](https://github.com/kubernetes/apiextensions-apiserver/blob/release-1.17/pkg/apis/apiextensions/v1/types_jsonschema.go#L27)
format: cidr - validates that string is valid IPv4 or IPv6 CIDR
Because we want to allow only one of them for each field value, adding a filter pattern solves this
In IPv4 CIDR case:
pattern: '^\d+\.' - pattern matches first IPv4 block + dot, first IPv6 block cannot be followed by dot
In IPv6 CIDR case:
pattern: ':' - pattern matches at least one colon in IPv6, there is no colon in IPv4
bug
Fixes an error during POD creation because CRD schema validation is erroneous for IPv6 related string fields in DanmNet, ClusternNetwork, TenantNetwork.
Causes …
> Fix CRD IPv4/IPv6 CIDR validation pattern to strict

- example/4_0_examples/10_good_deployment.yaml
- example/4_0_examples/11_allowed_default.yaml
- example/4_0_examples/12_not_allowed_default.yaml
- example/4_0_examples/9_wrong_deployment.yaml
- example/routes_and_proutes/pod_with_proutes.yaml
- example/svcwatcher_demo/deployments/external_client.yaml
- example/svcwatcher_demo/deployments/internal_processor.yaml
- example/svcwatcher_demo/deployments/loadbalancer.yaml
- integration/bootstrap_networks/lightweight/flannel.yaml
- integration/bootstrap_networks/production/flannel.yaml
- integration/cni_config/danm_rbac.yaml
- integration/cni_config/example_kubeconfig.yaml
- integration/manifests/netwatcher/netwatcher_ds.yaml
- integration/manifests/svcwatcher/0svcwatcher_rbac.yaml
- integration/manifests/svcwatcher/svcwatcher_ds.yaml
cleanup
When old `example` and `integration` manifests are used kubernetes emits deprecation warnings. This PR clears those warnings.
NONE
```release-note
NONE
```
> Fix kubernetes API deprecation in manifests

- pkg/netcontrol/netcontrol.go
This is needed to avoid relying on assumptions whether a specific version of client-go library fills it, or not.
> Explicitly set DanmNet API type into a network's TypeMeta upon interrogation

- crd/apis/danm/v1/types.go
- pkg/danmep/danmep.go
- pkg/danmep/ep.go
- user-guide.md
solves https://github.com/nokia/danm/issues/175
When the VFIO bound VF is tagged with a VLAN, we create an extra VLAN IF on top of the dummy with the same tag.
The VF's PCI ID is added to the dummy (VLAN too) as an Alias.
This mapping should be enough for applications to map allocations to the proper device.
> Enhancing dummy interface capabilities with VLAN and PCI ID information

- .dockerignore
- build_danm.sh
- deployment-guide.md
- deployment-installer-job.md
- integration/install/0danm-installer-rbac.yaml
- integration/install/danm-installer-config.yaml
- integration/install/danm-installer.yaml
- integration/manifests/cni_plugins/cni_plugins_ds.yaml
- integration/manifests/cni_plugins/cni_plugins_ds.yaml.tmpl
- integration/manifests/netwatcher/netwatcher_ds.yaml.tmpl
- integration/manifests/svcwatcher/svcwatcher_ds.yaml.tmpl
- integration/manifests/webhook/webhook-create-signed-cert.sh
- integration/manifests/webhook/webhook.yaml.tmpl
- scm/build/Dockerfile.install
- scm/build/cni_ds/entrypoint.sh
- scm/build/install/confd/conf.d/cni_plugins_ds.toml
- scm/build/install/confd/conf.d/danm-config.toml
- scm/build/install/confd/conf.d/default-net.toml
- scm/build/install/confd/conf.d/netwatcher_ds.toml
- scm/build/install/confd/conf.d/svcwatcher_ds.toml
- scm/build/install/confd/conf.d/webhool.toml
- scm/build/install/confd/templates/danm-config.yaml.tmpl
- scm/build/install/confd/templates/default-net.yaml.tmpl
- scm/build/install/install.sh
Adds an alternate method of installing by running a Kubernetes Job.
See file "deployment-installer-job.md" in this commit for a detailed
description of the job.
feature
A simple installer job
Fixes #35 
With this change in place, it might actually make sense to pre-build DANM and upload to DockerHub? That would even further simplify the deployment.
A Helm chart might be yet another option, but I don't know of a good way to do the Kubernetes CA integration (issuing the CSR, getting it signed) by Helm alone. It seems that that would still require a …
> Add installer job

- pkg/metacni/metacni.go
Before a CNI ADD is performed we unfortunetaly have to checkk if any DanmEps were already created for the exact same Pod, with the exact same UID.
This is because Kubelet can double invoke CNI ADDs without ever invoking CNI DEL in certain cases.
This results in unfortunate extra REST traffic, but is the only way to 100% guarantee correct cluster state.
> Adding obligatory cleanup to the beginning of every CNI ADD operation

- integration/install/0danm-installer-rbac.yaml
- integration/manifests/webhook/webhook-create-signed-cert.sh
As of Kubernetes 1.18, explicit RBAC authorization is needed for the
installer to approve a CSR (ie. to execute the "kubectl certificate
approve" command).
bug
Installer compatibility with k8s 1.18.
Ref. https://kubernetes.io/docs/setup/release/notes/#no-really-you-must-read-this-before-you-upgrade and https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#authorization
> Update installer job RBAC to grant approver permission

- integration/manifests/webhook/webhook-create-signed-cert.sh
- scm/build/Dockerfile
It seems that including the signerName in RBAC is optional in 1.17
(and before?), but required as of 1.18.
Including signerName in the CSR itself, is optional in 1.18 but
NOT supported in 1.17 or earlier.
Hence, removing signerName from the CSR creation again. This may need
to be revisited later.
bug
Bugfix to previous code commit regarding CSR signerName. Unfortunately, the previous commit,
while fixing an issue for 1.18, broke older releases :(
NONE
> Additional fix to installer CSR signername and webhook

- pkg/danmep/danmep.go
This is required to ensure when a previously allocated IP moves to another host the change is propagated throughout the fabric.
In case of IPv4 we achieve the same effect by sending a gARP Reply through the interface, but this mechanism does not exist for IPv6. Previously we thought it is because such mechanism happens automatically in the kernel, however as we recently found out this functionality seemed to be configurable via the ndisc_notify kernel setting:
https://sysctl-explorer.net/net/ipv6/ndisc_notify/
> Adding automatic setting of ndisc_notify kernel parameter to 1 on all DANM managed V6 interfaces

- .travis.yml
- scm/build/Dockerfile.install
Added arm64 support to travis-ci : 
1. Added arch: arm64 to .travis.yml
2. Downloaded arm64 specific releases in Dockerfile.install
> Added arm64 support to travis-ci

- pkg/danmep/ep.go
1: When VLAN is configured we only add the VF MAC to the final interface, and not for the underlay
Previously we added it to both. On kernel 4.14-4.18-4.19 this is okay, but maybe older kernels can't tolerate the same MAC added to multiple interfaces in the same netns?
2: Proper sysctl settings are now manually applied on the underlay dummy as well (i.e. IPv6 ON/OFF)
> Cosmetic / low-impact changes made to dummy kernel interface feature

- pkg/danmep/danmep.go
- pkg/danmep/ep.go
In this PR the post-processing done by DANM is restructured to accomodate CNIs which do not create kernel networking interfaces.
Userpsace CNIs, or various network config CNIs all belong to this category. When such a CNI is invoked through DANM, various post-processing errors related to automatically setting certain interface specific configs (v/, DAD, IP routes etc.) in the kernel would fail simply because the interface does not exist.
These issues are universally solved by checking for the presence of a kernel interface first, and only initiating post-processing if one is found.
> Restrict post-processing to kernel network interfaces

- integration/manifests/webhook/webhook.yaml
- integration/manifests/webhook/webhook.yaml.tmpl
- pkg/syncher/syncher.go
- test.lonyal
- test/uts/syncher_test/syncher_test.go
bug
During CNI ADD/DEL operations DANM waits 30 seconds to finish all
the delegated CNI tasks and DanmEp processing. In case the webhook
is too slow to respond, DANM timeouts without knowing the reason.
The webhook REST call timeout is lowered to 25 seconds (by default
it is 30 sec), so its timeout event can arrive back to DANM, which
can log that error message.
Related to #144, which is still a valid issue.
No.
> Adjust webhook timeout & Fix CNI timeout error message

- integration/install/0danm-installer-rbac.yaml
bug
> cleanup
> design
> failing-test
> feature
Modified rbac file for danm installer. Fix support for danm installation via job.
Fixes #266
Verified on k8s v1.21.8
yes
```release-note
* Add k8s.cni.cncf.io api group for danm installer rbac.
* Add bind verb to rbac.authorization.k8s.io for danm installer.
* Add patch, approve and delete support to certificates.k8s.io api group for danm installer.
```
> Fix authorization modes and add k8s.cni.cncf.io authorization group to danm installer rbac
